Eleição do Chefe do Conselho
lhc/estatuto pull request #4
Opened 2019-03-19 00:35 UTC by rennerocha

Indicar que a eleição é feita no Conselho e define o mandato do Chefe de Conselho.
Também é importante que ele não faça parte da diretoria executiva.

2019-03-22 02:17 UTC, inconstante requested changes

2019-03-22 02:17 UTC, gftg85 commented on src/estatuto.md
> +    de 01 (um) ano sendo permitida a recondução.
Se o Chefe do Conselho será eleito pelos Membros do Conselho, e se para se tornar Membro do Conselho um Associado precisa fazer requisição por escrita ao Chefe do Conselho, não temos um problema de dependência circular?

2019-03-27 19:29 UTC, marinello commented on src/estatuto.md
> +    de 01 (um) ano sendo permitida a recondução.
Sim, mas acredito que apenas na fase transitória. Seria preciso adicionar o caso especial, por exemplo na assembleia de fundação qualquer um poderia ser incluído no conselho se assim desejar.

2019-03-28 19:38 UTC, carloscosta commented
Conforme decidido em reunião, o chefe do conselho será eleito junto com o presidente e os diretores fiscal e administrativo, terá mandato regular.

2019-03-28 19:38 UTC, closed without merging